# fly.toml app configuration file generated for casualgraph on 2026-07-08T07:44:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'casualgraph'
primary_region = 'syd'

[build]

[env]
  AUTH_DB_PATH = '/data/auth.db'
  DATA_DIR = '/data'
  EXTRACTION_MAX_WORKERS = '4'
  INGESTION_JOB_MAX_WORKERS = '1'
  PORT = '8000'

[[mounts]]
  source = 'casualgraph_data'
  destination = '/data'
  initial_size = '3gb'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
