import type { Lang } from '../../i18n/core';
import { SCENARIO_EN } from '../../i18n/scenarios.en';

const SCENARIOS_ZH = Object.keys(SCENARIO_EN).filter(name => name !== '其他商事合同');

export type AgentCopy = { id: string; name: string; role: string; tone: 'violet' | 'cyan' | 'pink' | 'blue' | 'white' };
export type StepCopy = { title: string; body: string };
export type CapabilityCopy = { title: string; body: string };

/** Everything the landing page says, in both languages, side by side. */
const zh = {
  title: '法务 Agent · 多 Agent 合同审查',
  hero: {
    badge: '全新 · 多 Agent 协同合同审查',
    line1: '你的 AI 法务团队',
    line2: '逐条守护每一份合同',
    reviewing: '正在审查',
    words: SCENARIOS_ZH,
    sub: '上传合同，先自动脱敏；法律风险、商业利益、公司规范多个 Agent 并行审查，每条意见都有依据与修改建议，确认后一键导出 Word 修订版。',
    primary: '开始审查合同',
    secondary: '看它如何工作',
    chips: ['先脱敏，后分析', 'Word 原生修订', 'GPT · Claude · DeepSeek · Kimi · GLM'],
    stats: [
      { value: 20, label: '类合同场景' },
      { value: 5, label: '个协作 Agent' },
      { value: 4, label: '档审查深度' },
      { value: 12, label: '路模型并发' },
    ],
    pause: '暂停背景动效',
    play: '播放背景动效',
    scroll: '向下探索',
  },
  scenarios: {
    eyebrow: '场景覆盖',
    title: '20 类商事合同，\n按你的立场审查',
    sub: '选择合同类型与我方身份，审查清单、风险判断和修改方向随之切换。',
  },
  agents: {
    eyebrow: '多 Agent 协作',
    title: '五个专业 Agent，\n同时读同一份合同',
    sub: '每个 Agent 只在自己的职责内下判断，再由其他 Agent 复核、交叉印证；结论不确定时，会明确告诉你还缺什么。',
    center: '你的合同',
    feedTitle: '实时审查动态',
    caption: '示意动画，并非真实合同的审查结果。',
    list: [
      { id: 'legal', name: '法律风险审查', role: '判断效力、法定义务与可执行性，并写明法律依据。', tone: 'violet' },
      { id: 'commercial', name: '公司利益审查', role: '站在我方角色，看付款、交付、责任与退出成本。', tone: 'cyan' },
      { id: 'policy', name: '公司规范审查', role: '对照你维护的内部制度，标出偏离与审批要求。', tone: 'pink' },
      { id: 'critic', name: '证据与覆盖复核', role: '复核依据是否成立，审查要点是否全部覆盖。', tone: 'blue' },
      { id: 'arbiter', name: '全文协调与冲突检查', role: '发现条款之间的冲突，合并重复意见。', tone: 'white' },
    ] as AgentCopy[],
    feed: [
      '第 8.2 条 违约金约定可能明显过高，建议调整 · 依据《民法典》第五百八十五条',
      '第 4.1 条 付款早于验收，我方资金风险偏高 · 建议改为验收后付款',
      '第 6 条 付款审批流程与公司《采购管理办法》不一致',
      '已核对 18/18 项审查要点 · 2 条依据待你确认',
      '交付期限在第 3 条与附件一中不一致 · 已合并为 1 条意见',
    ],
  },
  workflow: {
    eyebrow: '工作流程',
    title: '从上传到导出，\n每一步都看得见',
    steps: [
      { title: '上传合同', body: '支持 DOCX、PDF（文本型）、TXT，单个文件 10 MB 以内，原件加密保存。' },
      { title: '自动脱敏', body: '姓名、电话、账号、金额等敏感信息先替换为占位符，你可以对照原件逐处核对。' },
      { title: '设定立场', body: '选择合同类型、我方身份与审查档位，补充交易背景；模型分析前需要你单独授权。' },
      { title: '多 Agent 审查', body: '多个 Agent 并行审查、检索法规、交叉复核，进度与每一步实时可见。' },
      { title: '逐条处理，导出修订', body: '逐条采纳、编辑或保留修改建议，核验后导出带修订痕迹的 Word。' },
    ] as StepCopy[],
    mock: {
      file: '供货合同（2026 版）.docx',
      uploading: '加密上传中…',
      stored: '已加密保存',
      redactTitle: '脱敏核对',
      redactLines: [
        ['甲方：', '示例科技有限公司', '【主体1】'],
        ['联系人：', '张三', '【姓名1】'],
        ['电话：', '138 0000 0000', '【电话1】'],
        ['合同总价：人民币', '1,280,000 元', '【金额1】'],
        ['收款账户：', '6222 0000 0000 0000', '【账号1】'],
      ],
      redactDone: '已脱敏 5 处 · 可对照原件',
      setupFields: [['合同类型', '采购合同'], ['我方身份', '采购方']],
      tierLabel: '审查档位',
      tiers: ['极速', '快速', '标准', '深度'],
      modelLabel: '审查模型',
      consent: '同意将脱敏文本提交所选模型分析',
      agentsTitle: '审查进度',
      clause: '第 4.1 条 · 付款',
      risk: '高风险',
      before: '甲方应在',
      deleted: '合同签订后 5 日内',
      inserted: '验收合格后 30 日内',
      after: '支付全部价款。',
      actions: ['采纳', '编辑', '保留'],
      export: '导出 Word 修订版',
      exported: '已生成 · 3 处修订痕迹',
    },
  },
  capabilities: {
    eyebrow: '核心能力',
    title: '为真实的合同工作而生',
    list: [
      { title: '隐私优先', body: '原件加密保存，模型只接收脱敏文本；上传与模型分析分别授权。' },
      { title: '按立场审查', body: '20 类合同场景，按我方身份切换审查清单与风险判断。' },
      { title: '四档审查深度', body: '极速、快速、标准、深度，在速度与彻底之间按需选择。' },
      { title: '依据可追溯', body: '检索法规与官方来源，每条意见都标注依据和待核实的信息。' },
      { title: '公司规范库', body: '把内部合同制度写成规范，审查时自动对照，偏离一目了然。' },
      { title: 'Word 原生修订', body: '采纳的修改以修订痕迹写回 Word，原有格式保持不变。' },
      { title: '随时追问', body: '对任意批注继续提问，回答基于本次审查的合同与依据。' },
      { title: '多模型可选', body: 'GPT、Claude、DeepSeek、Kimi、GLM，按需选择审查模型。' },
    ] as CapabilityCopy[],
  },
  statement: {
    text: 'AI 负责不遗漏，\n你负责做决定。',
    sub: '每一条修改都需要你确认。审查结果仅供参考，不构成法律意见。',
  },
  cta: {
    title: '下一份合同，\n交给你的 AI 法务团队',
    sub: '上传一份合同，看看五个 Agent 如何逐条审查。合同审查为 Max 会员功能。',
    primary: '开始审查合同',
    secondary: '了解研究工作台',
  },
  footer: {
    tagline: '多 Agent 合同审查与证据研究。',
    product: '产品',
    company: '公司',
    links: { legal: '法务 Agent', research: '研究工作台', graph: '知识图谱', desktop: '桌面应用', about: '关于我们' },
    disclaimer: '审查结果仅供参考，不构成法律意见。',
    built: '在澳大利亚打造',
  },
};

type Copy = typeof zh;

const en: Copy = {
  title: 'Legal Agent · Multi-agent contract review',
  hero: {
    badge: 'New · Multi-agent contract review',
    line1: 'Your AI legal team,',
    line2: 'on every clause.',
    reviewing: 'Now reviewing',
    words: SCENARIOS_ZH.map(name => SCENARIO_EN[name]),
    sub: 'Upload a contract and it is redacted first. Specialist agents review legal risk, commercial exposure and company policy in parallel, back every finding with its basis and a suggested edit, and export a tracked-changes Word draft once you approve.',
    primary: 'Review a contract',
    secondary: 'See how it works',
    chips: ['Redacted before analysis', 'Native Word tracked changes', 'GPT · Claude · DeepSeek · Kimi · GLM'],
    stats: [
      { value: 20, label: 'contract scenarios' },
      { value: 5, label: 'collaborating agents' },
      { value: 4, label: 'review depths' },
      { value: 12, label: 'parallel model calls' },
    ],
    pause: 'Pause background motion',
    play: 'Play background motion',
    scroll: 'Scroll to explore',
  },
  scenarios: {
    eyebrow: 'Coverage',
    title: '20 kinds of commercial contract, reviewed from your side',
    sub: 'Pick the contract type and the party you represent; the checklist, the risk calls and the suggested edits follow.',
  },
  agents: {
    eyebrow: 'Multi-agent review',
    title: 'Five specialist agents read the same contract at once',
    sub: 'Each agent judges only what is in its remit, then the others check its work. When a conclusion is uncertain, it tells you what is missing instead of guessing.',
    center: 'Your contract',
    feedTitle: 'Live review feed',
    caption: 'Illustrative animation, not the review of a real contract.',
    list: [
      { id: 'legal', name: 'Legal risk', role: 'Validity, statutory duties and enforceability, with the law it relies on.', tone: 'violet' },
      { id: 'commercial', name: 'Commercial interest', role: 'Payment, delivery, liability and exit costs, from your side of the deal.', tone: 'cyan' },
      { id: 'policy', name: 'Company policy', role: 'Checks the internal policies you maintain and flags deviations and approvals.', tone: 'pink' },
      { id: 'critic', name: 'Evidence and coverage', role: 'Confirms each basis holds and every checklist item was covered.', tone: 'blue' },
      { id: 'arbiter', name: 'Whole-contract consistency', role: 'Finds conflicts between clauses and merges duplicate findings.', tone: 'white' },
    ],
    feed: [
      'Clause 8.2: liquidated damages may be excessive; suggest adjusting · Civil Code, Art. 585',
      'Clause 4.1: payment falls due before acceptance; high cash exposure · suggest paying on acceptance',
      'Clause 6: payment approval differs from the company procurement policy',
      '18 of 18 checklist items covered · 2 sources await your confirmation',
      'Delivery dates differ between clause 3 and Schedule 1 · merged into one finding',
    ],
  },
  workflow: {
    eyebrow: 'How it works',
    title: 'From upload to export, every step in view',
    steps: [
      { title: 'Upload', body: 'DOCX, text-based PDF or TXT up to 10 MB. The original is stored encrypted.' },
      { title: 'Redact', body: 'Names, phone numbers, accounts and amounts become placeholders first, and you can compare each one with the original.' },
      { title: 'Choose your side', body: 'Pick the contract type, your party and a review depth, add deal context, and authorise model analysis separately.' },
      { title: 'Multi-agent review', body: 'Agents review in parallel, look up the law and check each other, with progress and every step visible live.' },
      { title: 'Decide and export', body: 'Accept, edit or keep each suggestion, verify, and export a Word file with tracked changes.' },
    ],
    mock: {
      file: 'Supply Agreement (2026).docx',
      uploading: 'Encrypting upload…',
      stored: 'Stored encrypted',
      redactTitle: 'Redaction check',
      redactLines: [
        ['Party A: ', 'Example Technology Co., Ltd.', '[Entity 1]'],
        ['Contact: ', 'Zhang San', '[Name 1]'],
        ['Phone: ', '138 0000 0000', '[Phone 1]'],
        ['Total price: RMB ', '1,280,000', '[Amount 1]'],
        ['Account: ', '6222 0000 0000 0000', '[Account 1]'],
      ],
      redactDone: '5 items redacted · compare with original',
      setupFields: [['Contract type', 'Purchase agreement'], ['Our party', 'Buyer']],
      tierLabel: 'Review depth',
      tiers: ['Ultra-fast', 'Fast', 'Standard', 'Deep'],
      modelLabel: 'Model',
      consent: 'Send the redacted text to the selected model',
      agentsTitle: 'Review progress',
      clause: 'Clause 4.1 · Payment',
      risk: 'High risk',
      before: 'Party A shall pay the full price ',
      deleted: 'within 5 days of signing',
      inserted: 'within 30 days of acceptance',
      after: '.',
      actions: ['Accept', 'Edit', 'Keep'],
      export: 'Export tracked-changes Word',
      exported: 'Ready · 3 tracked changes',
    },
  },
  capabilities: {
    eyebrow: 'Capabilities',
    title: 'Built for real contract work',
    list: [
      { title: 'Privacy first', body: 'Originals are stored encrypted and models only see redacted text. Upload and model analysis are authorised separately.' },
      { title: 'From your side', body: '20 contract scenarios; the checklist and risk calls follow the party you represent.' },
      { title: 'Four review depths', body: 'Ultra-fast, fast, standard or deep: trade speed for thoroughness as you need.' },
      { title: 'Traceable basis', body: 'Searches statutes and official sources; every finding shows its basis and what still needs checking.' },
      { title: 'Your policies as rules', body: 'Write internal contract policies once; every review checks against them and flags deviations.' },
      { title: 'Native Word redlines', body: 'Accepted edits go back into Word as tracked changes, with the original formatting intact.' },
      { title: 'Ask follow-ups', body: 'Ask about any finding; answers draw on this contract and its sources.' },
      { title: 'Choose your model', body: 'Review with GPT, Claude, DeepSeek, Kimi or GLM.' },
    ],
  },
  statement: {
    text: 'The AI makes sure nothing is missed.\nYou make the call.',
    sub: 'Every change waits for your approval. Results are for reference only and are not legal advice.',
  },
  cta: {
    title: 'Hand your next contract to your AI legal team',
    sub: 'Upload a contract and watch five agents review it clause by clause. Contract review is part of the Max membership.',
    primary: 'Review a contract',
    secondary: 'Explore the research desk',
  },
  footer: {
    tagline: 'Multi-agent contract review and evidence research.',
    product: 'Product',
    company: 'Company',
    links: { legal: 'Legal Agent', research: 'Research desk', graph: 'Knowledge graph', desktop: 'Desktop app', about: 'About us' },
    disclaimer: 'Review results are for reference only and are not legal advice.',
    built: 'Built in Australia',
  },
};

export const COPY: Record<Lang, Copy> = { zh, en };
