import type { Lang } from '../../i18n/core';

export type StepCopy = { title: string; body: string };
export type AgentCopy = { name: string; role: string; sample: string };
export type TileCopy = { title: string; body: string };

/** Everything the landing page says, in both languages. Headlines carry their own line breaks. */
const zh = {
  title: '法务 Agent · 合同审查',
  hero: {
    eyebrow: '法务 Agent',
    title: '一支 AI 法务团队，\n审每一份合同。',
    sub: '上传合同，先自动脱敏。五个专业 Agent 并行审查，每条意见都附依据与修改建议。确认后，一键导出 Word 修订版。',
    primary: '开始审查合同',
    secondary: '了解工作流程',
    film: '产品演示：合同审查全流程',
    replay: '重播',
    pause: '暂停',
    play: '播放',
    note: '演示使用合成合同。',
  },
  redaction: {
    eyebrow: '隐私优先',
    title: '先脱敏。\n再分析。',
    sub: '姓名、电话、账号与金额，在任何模型看到合同之前就替换为占位符。原件加密保存，每一处都可以对照核对。',
    before: '脱敏前',
    after: '模型看到的',
    lines: [
      ['甲方：', '杭州云禾科技有限公司', '【主体1】'],
      ['联系人：', '张晓敏', '【姓名1】'],
      ['电话：', '138 2345 6789', '【电话1】'],
      ['合同总价：人民币', '1,280,000 元', '【金额1】'],
      ['收款账户：', '6222 0210 0088 5312', '【账号1】'],
    ],
    status: '已脱敏 5 处 · 可对照原件',
  },
  workflow: {
    eyebrow: '工作流程',
    title: '五步。\n每一步都看得见。',
    steps: [
      { title: '上传合同', body: '支持 DOCX、PDF（文本型）与 TXT，单个文件 10 MB 以内。原件加密保存。' },
      { title: '自动脱敏', body: '敏感信息先替换为占位符，逐处对照原件核对后再继续。' },
      { title: '设定立场', body: '选择合同类型、我方身份与审查档位，补充交易背景。模型分析前单独授权。' },
      { title: '多 Agent 审查', body: '多个 Agent 并行审查、检索法规、交叉复核，进度与每一步实时可见。' },
      { title: '逐条处理，导出修订', body: '逐条采纳、编辑或保留。核验后导出带修订痕迹的 Word。' },
    ] as StepCopy[],
    mock: {
      file: '采购合同（2026 版）.docx',
      uploading: '加密上传中…',
      stored: '已加密保存',
      redactTitle: '脱敏核对',
      redactLines: [
        ['甲方：', '杭州云禾科技有限公司', '【主体1】'],
        ['联系人：', '张晓敏', '【姓名1】'],
        ['电话：', '138 2345 6789', '【电话1】'],
        ['合同总价：人民币', '1,280,000 元', '【金额1】'],
        ['收款账户：', '6222 0210 0088 5312', '【账号1】'],
      ],
      redactDone: '已脱敏 5 处 · 可对照原件',
      setupFields: [['合同类型', '采购合同'], ['我方身份', '采购方']],
      tierLabel: '审查档位',
      tiers: ['极速', '快速', '标准', '深度'],
      modelLabel: '审查模型',
      consent: '同意将脱敏文本提交所选模型分析',
      agentsTitle: '审查进度',
      agents: ['法律风险审查', '公司利益审查', '公司规范审查', '证据与覆盖复核', '全文协调与冲突检查'],
      clause: '第 4.1 条 · 付款',
      risk: '高风险',
      before: '甲方应在',
      deleted: '合同签订后 5 日内',
      inserted: '验收合格后 30 日内',
      after: '支付全部价款。',
      actions: ['采纳修改', '编辑', '保留原文'],
      export: '导出 Word 修订版',
      exported: '已生成 · 2 处修订痕迹',
    },
  },
  agents: {
    eyebrow: '多 Agent 协作',
    title: '五个专业 Agent。\n各司其职，相互复核。',
    sub: '每个 Agent 只在自己的职责内下判断，再由其他 Agent 复核与交叉印证。结论不确定时，会说明还缺什么，而不是猜。',
    list: [
      { name: '法律风险审查', role: '判断效力、法定义务与可执行性，写明法律依据。', sample: '第 6.1 条 违约金约定过高 · 《民法典》第五百八十五条' },
      { name: '公司利益审查', role: '站在我方角色，看付款、交付、责任与退出成本。', sample: '第 4.1 条 付款早于验收，资金风险集中在我方' },
      { name: '公司规范审查', role: '对照你维护的内部制度，标出偏离与审批要求。', sample: '第 5 条 验收标准与《采购管理办法》不一致' },
      { name: '证据与覆盖复核', role: '复核每条依据是否成立，审查要点是否全部覆盖。', sample: '18/18 项要点已覆盖 · 2 条依据已核验' },
      { name: '全文协调与冲突检查', role: '发现条款之间的冲突，合并重复意见。', sample: '第 3 条与附件一交付期限不一致 · 已合并为 1 条' },
    ] as AgentCopy[],
    caption: '示例批注来自合成合同。',
    prev: '上一个',
    next: '下一个',
  },
  stats: {
    title: '为真实的合同工作而生。',
    items: [
      ['20', '类合同场景'],
      ['5', '个专业 Agent'],
      ['4', '档审查深度'],
      ['12', '路模型并发'],
    ],
  },
  tiers: {
    eyebrow: '审查深度',
    title: '四档深度。\n按合同的分量选择。',
    sub: '从几分钟的初筛到最彻底的专项审查，同一条流程，不同的投入。',
    columns: [
      { name: '极速', tag: '快速初筛', note: '一轮并行审查，直接给出意见与修改建议。' },
      { name: '快速', tag: '日常合同', note: '分组审查后，逐项独立复核。' },
      { name: '标准', tag: '推荐', note: '分组审查与法规检索同时进行，逐项复核后核对修改能否同时采用。' },
      { name: '深度', tag: '重要交易', note: '法律、商业与公司规范分别审查，再经独立复核与全文协调。' },
    ],
    rows: [
      ['分组并行审查', [true, true, true, true]],
      ['逐项独立复核', [false, true, true, true]],
      ['法规与官方来源检索', [false, false, true, true]],
      ['修改组合核验', [false, false, true, true]],
      ['法律、商业、规范分别审查', [false, false, false, true]],
      ['全文协调与冲突检查', [false, false, false, true]],
    ] as [string, boolean[]][],
    footnote: '极速审查的意见未经独立复核，采用前请逐条确认。',
  },
  capabilities: {
    eyebrow: '更多能力',
    title: '围绕合同工作，\n一应俱全。',
    tiles: [
      { title: '公司规范库', body: '把内部合同制度写成规范，每次审查自动对照，偏离一目了然。' },
      { title: 'Word 原生修订', body: '采纳的修改以修订痕迹写回 Word，原有格式保持不变。' },
      { title: '随时追问', body: '对任意批注继续提问，回答基于这份合同与它的依据。' },
      { title: '依据可追溯', body: '检索法规与官方来源，每条意见标注依据与待核实之处。' },
      { title: '20 类合同场景', body: '采购、销售、服务、保密、SaaS、租赁……按我方身份切换清单。' },
      { title: '交易背景', body: '补充履行阶段、附件状态与交易金额，审查更贴合实际。' },
    ] as TileCopy[],
    scenarios: ['采购', '销售', '服务', '保密', '软件开发', 'SaaS', '运维', '技术开发', '租赁', '经销', '代理', '物流', '仓储', '广告', '框架协议'],
    rules: ['付款须验收后支付', '违约金不超过 20%', '争议由我方所在地管辖'],
    question: '这条违约金为什么可能过高？',
    answer: '约定为合同总价的 50%，明显高于可能的损失，依据《民法典》第五百八十五条可请求减少。',
    cite: ['《民法典》第五百八十五条', '官方来源 · 已核验'],
    redline: ['甲方应在', '合同签订后 5 日内', '验收合格后 30 日内', '支付全部价款。'],
    context: [['履行阶段', '谈判中'], ['关键附件', '已提供'], ['交易金额', '1,280,000 CNY']],
  },
  privacy: {
    eyebrow: '隐私',
    title: '隐私，\n从设计开始。',
    items: [
      { title: '原件加密保存', body: '上传的合同加密存储，脱敏文本与原件分开保管。' },
      { title: '模型只见脱敏文本', body: '任何模型都不会看到脱敏前的合同。' },
      { title: '分别授权', body: '上传与模型分析分别确认；切换模型，需要重新授权。' },
    ] as TileCopy[],
  },
  models: {
    title: '选择你信任的模型。',
    sub: 'GPT、Claude、DeepSeek、Kimi 与 GLM，经 YData 网关接入，按需切换。每次审查固定使用所选模型。',
    list: ['GPT', 'Claude', 'DeepSeek', 'Kimi', 'GLM'],
  },
  statement: {
    text: 'AI 负责不遗漏。\n你负责做决定。',
    sub: '每一处修改都需要你确认。审查结果仅供参考，不构成法律意见。',
  },
  cta: {
    title: '下一份合同，\n从这里开始。',
    sub: '合同审查为 Max 会员功能。',
    primary: '开始审查合同',
    secondary: '了解研究工作台',
  },
  footer: {
    tagline: '多 Agent 合同审查与证据研究。',
    product: '产品',
    company: '公司',
    links: { legal: '法务 Agent', research: '研究工作台', graph: '知识图谱', desktop: '桌面应用', about: '关于我们' },
    disclaimer: '审查结果仅供参考，不构成法律意见。',
    built: '在澳大利亚打造',
  },
};

type Copy = typeof zh;

const en: Copy = {
  title: 'Legal Agent · Contract review',
  hero: {
    eyebrow: 'Legal Agent',
    title: 'An AI legal team\nfor every contract.',
    sub: 'Upload a contract and it is redacted first. Five specialist agents review it in parallel, and every finding comes with its basis and a suggested edit. Approve, then export a tracked‑changes Word file.',
    primary: 'Review a contract',
    secondary: 'See how it works',
    film: 'Product demo: a contract review from upload to export',
    replay: 'Replay',
    pause: 'Pause',
    play: 'Play',
    note: 'Demo uses a synthetic contract.',
  },
  redaction: {
    eyebrow: 'Privacy first',
    title: 'Redacted first.\nThen reviewed.',
    sub: 'Names, phone numbers, account numbers and amounts become placeholders before any model sees the contract. The original stays encrypted, and you can check every redaction against it.',
    before: 'Original',
    after: 'What the model sees',
    lines: [
      ['Party A: ', 'Hangzhou Yunhe Technology Co., Ltd.', '[Entity 1]'],
      ['Contact: ', 'Zhang Xiaomin', '[Name 1]'],
      ['Phone: ', '138 2345 6789', '[Phone 1]'],
      ['Total price: RMB ', '1,280,000', '[Amount 1]'],
      ['Account: ', '6222 0210 0088 5312', '[Account 1]'],
    ],
    status: '5 items redacted · compare with the original',
  },
  workflow: {
    eyebrow: 'How it works',
    title: 'Five steps.\nEvery one in view.',
    steps: [
      { title: 'Upload', body: 'DOCX, text-based PDF or TXT up to 10 MB. The original is stored encrypted.' },
      { title: 'Redact', body: 'Sensitive details become placeholders first; check each one against the original before going on.' },
      { title: 'Choose your side', body: 'Pick the contract type, your party and a review depth, and add deal context. Model analysis is authorised separately.' },
      { title: 'Multi-agent review', body: 'Agents review in parallel, look up the law and check each other, with progress and every step visible live.' },
      { title: 'Decide and export', body: 'Accept, edit or keep each suggestion. Verify, then export a Word file with tracked changes.' },
    ],
    mock: {
      file: 'Purchase Agreement (2026).docx',
      uploading: 'Encrypting upload…',
      stored: 'Stored encrypted',
      redactTitle: 'Redaction check',
      redactLines: [
        ['Party A: ', 'Hangzhou Yunhe Technology Co., Ltd.', '[Entity 1]'],
        ['Contact: ', 'Zhang Xiaomin', '[Name 1]'],
        ['Phone: ', '138 2345 6789', '[Phone 1]'],
        ['Total price: RMB ', '1,280,000', '[Amount 1]'],
        ['Account: ', '6222 0210 0088 5312', '[Account 1]'],
      ],
      redactDone: '5 items redacted · compare with original',
      setupFields: [['Contract type', 'Purchase agreement'], ['Our party', 'Buyer']],
      tierLabel: 'Review depth',
      tiers: ['Ultra-fast', 'Fast', 'Standard', 'Deep'],
      modelLabel: 'Model',
      consent: 'Send the redacted text to the selected model',
      agentsTitle: 'Review progress',
      agents: ['Legal risk', 'Commercial interest', 'Company policy', 'Evidence and coverage', 'Whole-contract consistency'],
      clause: 'Clause 4.1 · Payment',
      risk: 'High risk',
      before: 'Party A shall pay the full price ',
      deleted: 'within 5 days of signing',
      inserted: 'within 30 days of acceptance',
      after: '.',
      actions: ['Accept edit', 'Edit', 'Keep original'],
      export: 'Export tracked-changes Word',
      exported: 'Ready · 2 tracked changes',
    },
  },
  agents: {
    eyebrow: 'Multi-agent review',
    title: 'Five specialist agents.\nEach with a remit, checking each other.',
    sub: 'Each agent judges only what is within its remit, then the others verify and cross-check its work. When a conclusion is uncertain, it says what is missing instead of guessing.',
    list: [
      { name: 'Legal risk', role: 'Validity, statutory duties and enforceability, with the law it relies on.', sample: 'Clause 6.1 Liquidated damages excessive · Civil Code, Art. 585' },
      { name: 'Commercial interest', role: 'Payment, delivery, liability and exit costs, from your side of the deal.', sample: 'Clause 4.1 Payment before acceptance; the cash risk sits with us' },
      { name: 'Company policy', role: 'Checks the internal policies you maintain and flags deviations and approvals.', sample: 'Clause 5 Acceptance criteria conflict with the Procurement Policy' },
      { name: 'Evidence and coverage', role: 'Confirms each basis holds and every checklist item was covered.', sample: '18/18 items covered · 2 sources verified' },
      { name: 'Whole-contract consistency', role: 'Finds conflicts between clauses and merges duplicate findings.', sample: 'Delivery dates differ between clause 3 and Schedule 1 · merged into one' },
    ],
    caption: 'Sample findings come from a synthetic contract.',
    prev: 'Previous',
    next: 'Next',
  },
  stats: {
    title: 'Built for real contract work.',
    items: [
      ['20', 'contract scenarios'],
      ['5', 'specialist agents'],
      ['4', 'review depths'],
      ['12', 'parallel model calls'],
    ],
  },
  tiers: {
    eyebrow: 'Review depth',
    title: 'Four depths.\nMatched to the contract.',
    sub: 'From a quick first pass to the most thorough specialist review: the same workflow, a different investment.',
    columns: [
      { name: 'Ultra-fast', tag: 'First pass', note: 'One parallel pass that returns findings and suggested edits directly.' },
      { name: 'Fast', tag: 'Everyday contracts', note: 'Reviews in groups, then verifies each finding independently.' },
      { name: 'Standard', tag: 'Recommended', note: 'Reviews in groups while researching the law, verifies each finding, then checks that the edits can be adopted together.' },
      { name: 'Deep', tag: 'Important deals', note: 'Separate legal, commercial and policy reviews, then independent verification and a whole-contract pass.' },
    ],
    rows: [
      ['Parallel group review', [true, true, true, true]],
      ['Independent verification of each finding', [false, true, true, true]],
      ['Statute and official-source research', [false, false, true, true]],
      ['Combined-edit verification', [false, false, true, true]],
      ['Separate legal, commercial and policy reviews', [false, false, false, true]],
      ['Whole-contract consistency pass', [false, false, false, true]],
    ],
    footnote: 'Ultra-fast findings are not independently verified; confirm each one before adopting it.',
  },
  capabilities: {
    eyebrow: 'More',
    title: 'Everything around\nthe contract.',
    tiles: [
      { title: 'Company policies', body: 'Write internal contract policies once; every review checks against them and flags deviations.' },
      { title: 'Native Word redlines', body: 'Accepted edits go back into Word as tracked changes, with the original formatting intact.' },
      { title: 'Ask follow-ups', body: 'Ask about any finding; answers draw on this contract and its sources.' },
      { title: 'Traceable basis', body: 'Searches statutes and official sources; every finding shows its basis and what still needs checking.' },
      { title: '20 contract scenarios', body: 'Purchase, sales, services, NDA, SaaS, lease and more; the checklist follows the party you represent.' },
      { title: 'Deal context', body: 'Add the performance stage, attachment status and deal value so the review fits the real transaction.' },
    ],
    scenarios: ['Purchase', 'Sales', 'Services', 'NDA', 'Software', 'SaaS', 'Support', 'R&D', 'Lease', 'Distribution', 'Agency', 'Logistics', 'Warehousing', 'Advertising', 'Framework'],
    rules: ['Pay only after acceptance', 'Damages capped at 20%', 'Disputes heard where we are'],
    question: 'Why might this penalty be too high?',
    answer: 'It is set at 50% of the contract price, well above the likely loss; under Civil Code Art. 585 it can be reduced on request.',
    cite: ['Civil Code, Art. 585', 'Official source · verified'],
    redline: ['Party A shall pay the full price ', 'within 5 days of signing', 'within 30 days of acceptance', '.'],
    context: [['Stage', 'Negotiating'], ['Attachments', 'Provided'], ['Deal value', '1,280,000 CNY']],
  },
  privacy: {
    eyebrow: 'Privacy',
    title: 'Privacy,\nby design.',
    items: [
      { title: 'Originals stay encrypted', body: 'Uploaded contracts are stored encrypted; redacted text and originals are kept apart.' },
      { title: 'Models see only redacted text', body: 'No model ever sees the contract before redaction.' },
      { title: 'Separate authorisation', body: 'Upload and model analysis are confirmed separately; switching models asks again.' },
    ],
  },
  models: {
    title: 'Choose the model you trust.',
    sub: 'GPT, Claude, DeepSeek, Kimi and GLM through the YData gateway; switch as you need. Each review runs on the model you selected.',
    list: ['GPT', 'Claude', 'DeepSeek', 'Kimi', 'GLM'],
  },
  statement: {
    text: 'The AI makes sure nothing is missed.\nYou make the call.',
    sub: 'Every change waits for your approval. Results are for reference only and are not legal advice.',
  },
  cta: {
    title: 'Your next contract\nstarts here.',
    sub: 'Contract review is part of the Max membership.',
    primary: 'Review a contract',
    secondary: 'Explore the research desk',
  },
  footer: {
    tagline: 'Multi-agent contract review and evidence research.',
    product: 'Product',
    company: 'Company',
    links: { legal: 'Legal Agent', research: 'Research desk', graph: 'Knowledge graph', desktop: 'Desktop app', about: 'About us' },
    disclaimer: 'Review results are for reference only and are not legal advice.',
    built: 'Built in Australia',
  },
};

export const COPY: Record<Lang, Copy> = { zh, en };
